name: CI/CD to Local IIS

on:
  push:
    branches:
      - master # 監聽主分支變更，您可以改成任何分支

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the project
      run: dotnet publish -c Release -o ./publish

    - name: Copy files to IIS server
      run: |
        # 使用 PowerShell 將發佈檔案複製到 IIS 伺服器
        $source = "$env:GITHUB_WORKSPACE\publish\*"
        $destination = "\\${{ secrets.IIS_HOST }}\C$\inetpub\wwwroot\test3"
        $username = "DESKTOP-K0JLNQN\Administrator"
        $password = "0310"
         
        # 使用 New-PSDrive 創建一個新的驅動器
        $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ($username, $securePassword)
        New-PSDrive -Name Z -PSProvider FileSystem -Root $destination -Credential $credential
        
        # 複製檔案
        Copy-Item -Path $source -Destination Z:\ -Recurse
        
        # 移除驅動器
        Remove-PSDrive -Name Z
